name: CICD Workflow1
on:
   workflow_dispatch
jobs:
   Build:
      runs-on: self-hosted
      steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
          
      - name: Maven Install
        run: |
           sudo apt update -y
           sudo apt install maven -y
           
      - name: Maven Clean package
        run: |
           mvn clean package
      - name: Install Trivy
        run: |
          wget https://github.com/aquasecurity/trivy/releases/download/v0.67.2/trivy_0.67.2_Linux-64bit.deb
          sudo dpkg -i trivy_0.67.2_Linux-64bit.deb

      - name: Trivy FS Scan
        run: trivy fs --format table -o fs-report.json .
        
      - name: SonarQube Analysis
        run: mvn sonar:sonar
