name: CICD-PIPELINE-FINAL

on:
  workflow_dispatch:

jobs:

  compile:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Install Maven
        run: |
          sudo apt update -y
          sudo apt install maven -y

      - name: Build with Maven
        run: mvn -B clean package

      # Upload WAR file
      - name: Upload WAR Artifact
        uses: actions/upload-artifact@v4
        with:
          name: war-file
          path: target/maven-web-application.war


  sonarqube:
    runs-on: self-hosted
    needs: compile
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: SonarQube Analysis
        run: |
          mvn sonar:sonar \
            -Dsonar.host.url=http://98.93.30.124:9000 \
            -Dsonar.login=${{ secrets.SONAR_TOKEN }}


  security-check:
    runs-on: self-hosted
    needs: sonarqube
    steps:
      - uses: actions/checkout@v4

      - name: Install Trivy
        run: |
          wget https://github.com/aquasecurity/trivy/releases/download/v0.67.2/trivy_0.67.2_Linux-64bit.deb
          sudo dpkg -i trivy_0.67.2_Linux-64bit.deb

      - name: Trivy FS Scan
        run: trivy fs --format table -o fs-report.json .


  docker-build:
    runs-on: self-hosted
    needs: security-check
    steps:
      - uses: actions/checkout@v4

      # Download WAR generated from compile job
      - name: Download WAR Artifact
        uses: actions/download-artifact@v4
        with:
          name: war-file
          path: target

      # Login to Docker Hub
      - name: Docker Login
        run: echo "${{ secrets.DOCKER_HUB_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_HUB_USERNAME }}" --password-stdin

      # Build Docker Image
      - name: Build Docker Image
        run: |
          docker build -t ${{ secrets.Docker_Repository }}:${{ github.sha }} .

      # Push Image
      - name: Push images to Docker Hub
        run: |
          docker push ${{ secrets.Docker_Repository }}:${{ github.sha }}
