name: CICD Pipeline 3

on:
  workflow_dispatch:

jobs:

  compile:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: install maven
        run: |
          sudo apt update
          sudo apt install maven -y

      - name: Build with Maven
        run: mvn -B clean package

      - name: Show target dir (debug)
        run: |
          echo ">>> listing target:"
          ls -la target || true
          du -sh target || true

      - name: Upload WAR artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-war
          path: target/maven-web-application.war

  sonarqube:
    runs-on: self-hosted
    needs: compile
    steps:
      - name: SonarQube Analysis
        run: mvn sonar:sonar

  security-check:
    runs-on: self-hosted
    needs: sonarqube
    steps:
      - name: Install Trivy
        run: |
          wget https://github.com/aquasecurity/trivy/releases/download/v0.67.2/trivy_0.67.2_Linux-64bit.deb
          sudo dpkg -i trivy_0.67.2_Linux-64bit.deb

      - name: Trivy FS Scan
        run: trivy fs --format table -o fs-report.json .

  docker-build:
    runs-on: self-hosted
    needs: security-check
    steps:
      - uses: actions/checkout@v4

      - name: Download WAR artifact
        uses: actions/download-artifact@v4
        with:
          name: app-war
          path: target

      - name: Debug workspace
        run: |
          echo "PWD: $(pwd)"
          echo "Listing repo root:"
          ls -la
          echo "Listing target:"
          ls -la target || true
          du -sh .

      - name: Build Docker Image
        run: |
          docker build -t ${{ secrets.Docker_Repository }}:${{ github.sha }} .

      - name: Push images to Docker Hub
        run: |
          docker push ${{ secrets.Docker_Repository }}:${{ github.sha }}
