name: CICD Workflow1
on:
   workflow_dispatch
jobs:
   Build:
      runs-on: self-hosted
      steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
          
      - name: Maven Install
        run: |
           sudo apt update -y
           sudo apt install maven -y
           
      - name: Maven Clean packag
        run: |
           mvn clean package
   Security-check:
      runs-on: self-hosted
      needs: Build
      steps:
         - name: Install Trivy
           run: |
              wget https://github.com/aquasecurity/trivy/releases/download/v0.67.2/trivy_0.67.2_Linux-64bit.deb
              sudo dpkg -i trivy_0.67.2_Linux-64bit.deb

         - name: Trivy FS Scan
           run: trivy fs --format table -o fs-report.json .
   SonarQube-check:
      runs-on: self-hosted
      needs:  Security-check
      steps:
         - name: SonarQube Analysis
           run: mvn sonar:sonar
   Docker-Push:
      runs-on: self-hosted
      needs: SonarQube-check
      steps:
         - name: Docker registry
           run: |
             docker build -t ${{ secrets.Docker_Repository }}:${{ github.sha }} .
